# Generated by Django 5.0.7 on 2024-10-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='usdt_type',
            field=models.CharField(choices=[('TRC20', 'TRC20'), ('ERC20', 'ERC20')], default='TRC20', max_length=10),
        ),
    ]
