# Generated by Django 5.0.7 on 2024-10-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='balance_type',
            field=models.CharField(default='Deposit', max_length=50),
        ),
    ]
