# Generated by Django 5.0.7 on 2024-10-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_deposit_balance_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='withdrawal_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
