# Generated by Django 5.0.7 on 2024-10-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_balance_daily_profit_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsPercentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_savings_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Enter percentage for total savings', max_digits=5)),
                ('daily_savings_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Enter percentage for daily savings', max_digits=5)),
                ('monthly_savings_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Enter percentage for monthly savings', max_digits=5)),
                ('yearly_savings_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Enter percentage for yearly savings', max_digits=5)),
            ],
            options={
                'verbose_name': 'Savings Percentage',
                'verbose_name_plural': 'Savings Percentages',
            },
        ),
    ]
