# Generated by Django 5.0.7 on 2024-10-13 03:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_savingspercentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSavings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('profit_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Savings',
                'verbose_name_plural': "Users' Savings",
            },
        ),
    ]
