# Generated by Django 5.0.7 on 2024-10-13 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_usersavings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingspercentage',
            name='total_savings_percentage',
        ),
    ]
