# Generated by Django 5.0.7 on 2024-10-13 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_savingspercentage_total_savings_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_savings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.usersavings')),
            ],
            options={
                'verbose_name': 'Savings Transaction',
                'verbose_name_plural': 'Savings Transactions',
            },
        ),
    ]
