# Generated by Django 5.0.7 on 2024-10-13 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_savingstransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersavings',
            name='is_daily_savings_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersavings',
            name='is_monthly_savings_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersavings',
            name='is_yearly_savings_active',
            field=models.BooleanField(default=False),
        ),
    ]
