# Generated by Django 5.0.7 on 2024-10-13 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_usersavings_is_daily_savings_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavingsTransaction',
        ),
    ]
